name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle (skip tests)
        run: ./gradlew build -x test

      - name: Confirm JAR exists
        run: ls -lh build/libs

      - name: Copy JAR and Dockerfile to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 3.106.231.215
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          source: |
            build/libs/*.jar
            Dockerfile
          target: /home/ec2-user/app

      - name: SSH and deploy with Docker
        uses: appleboy/ssh-action@master
        with:
          host: 3.106.231.215
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ec2-user/app
            mv build/libs/*.jar app.jar
            docker stop springboot-app || true
            docker rm springboot-app || true
            docker build -t springboot-app .
            docker run -d -p 8080:8080 --name springboot-app springboot-app
